import { ComponentSchema } from '../../../lib/schema-registry.js';

// Auto-registering Article component schema
export const ArticlePageComponentDefinition = ComponentSchema({
  key: 'ArticlePage',
  displayName: 'Article',
  description: '',
  baseType: 'page',
  sortOrder: 0,
  mayContainTypes: ['*'],
  mediaFileExtensions: [],
  compositionBehaviors: [],
  properties: {
    PromoImage: {
      type: 'contentReference',
      displayName: 'Promo Image',
      description: '',
      localized: true,
      required: false,
      group: 'Information',
      sortOrder: -100,
      editorSettings: {},
      allowedTypes: ['Image'],
      restrictedTypes: [],
    },
    Heading: {
      type: 'string',
      displayName: 'Heading',
      description: '',
      localized: true,
      required: false,
      group: 'Information',
      sortOrder: 0,
      editorSettings: {},
      indexingType: 'searchable',
    },
    SubHeading: {
      type: 'string',
      displayName: 'Sub Heading',
      description: '',
      localized: true,
      required: false,
      group: 'Information',
      sortOrder: 0,
      editorSettings: {},
      indexingType: 'searchable',
    },
    SeoSettings: {
      type: 'component',
      displayName: 'SEO Settings',
      description: '',
      localized: false,
      required: false,
      group: 'SeoSettings',
      sortOrder: 0,
      editorSettings: {},
      contentType: 'PageSeoSettings',
    },
    PageAdminSettings: {
      type: 'component',
      displayName: 'Page Admin Settings',
      description: '',
      localized: false,
      required: false,
      group: 'AdminSettings',
      sortOrder: 10,
      editorSettings: {},
      contentType: 'PageAdminSettings',
    },
    Author: {
      type: 'string',
      displayName: 'Author',
      description: '',
      localized: false,
      required: false,
      group: 'Information',
      sortOrder: 100,
      editorSettings: {},
      format: 'shortString',
      indexingType: 'searchable',
    },
    AuthorEmail: {
      type: 'string',
      displayName: 'Author Email',
      description: '',
      localized: false,
      required: false,
      group: 'Information',
      sortOrder: 150,
      editorSettings: {},
      indexingType: 'searchable',
    },
    Body: {
      type: 'string',
      displayName: 'Body',
      description: '',
      localized: true,
      required: false,
      group: 'Information',
      sortOrder: 200,
      editorSettings: {},
      format: 'html',
      indexingType: 'searchable',
    },
  },
});

// Function to serialize to JSON (returns a copy that can be safely modified)
export function serializeArticlePageToJSON() {
  return JSON.parse(JSON.stringify(ArticlePageComponentDefinition));
}
