import { ComponentSchema } from '../../../../lib/schema-registry.js';

// Auto-registering Site Styles component schema
export const SiteStylesComponentDefinition = ComponentSchema({
  key: 'SiteStyles',
  displayName: 'Site Styles',
  description: 'Manage site colors and other display attributes via the CMS',
  baseType: 'component',
  sortOrder: 0,
  mayContainTypes: [],
  mediaFileExtensions: [],
  compositionBehaviors: [],
  properties: {
    primary: {
      type: 'string',
      displayName: 'color-primary',
      description: 'Primary brand color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 10,
      editorSettings: {},
      format: 'shortString',
    },
    radiusSelector: {
      type: 'string',
      displayName: 'Radius - Selector (checkbox, toggle, badge, etc)',
      description: 'Border radius for selectors like checkbox, toggle, badge, etc',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 10,
      editorSettings: {},
      format: 'selectOne',
      enum: {
        values: [
          {
            displayName: 'Default',
            value: '',
          },
          {
            displayName: 'xs',
            value: '0rem',
          },
          {
            displayName: 's',
            value: '0.25rem',
          },
          {
            displayName: 'md',
            value: '0.5rem',
          },
          {
            displayName: 'lg',
            value: '1rem',
          },
          {
            displayName: 'xl',
            value: '2rem',
          }
        ],
      },
    },
    SiteStylesDomain: {
      type: 'string',
      displayName: 'Site Domain',
      description: 'Domain (format: www.mysite.com) to associate with these Site Styles',
      localized: false,
      required: true,
      group: 'Information',
      sortOrder: 10,
      editorSettings: {},
      indexingType: 'searchable',
      pattern: '^((([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,})|localhost)(:[0-9]+)?$',
    },
    textXs: {
      type: 'string',
      displayName: 'text-xs',
      description: 'Text size: xs',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 10,
      editorSettings: {},
      format: 'shortString',
    },
    primaryContent: {
      type: 'string',
      displayName: 'color-primary-content',
      description: 'Foreground content color to use on primary color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 20,
      editorSettings: {},
      format: 'shortString',
    },
    radiusField: {
      type: 'string',
      displayName: 'Radius - Field (button, input, select, tab)',
      description: 'Border radius for fields like input, select, tab, etc',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 20,
      editorSettings: {},
      format: 'selectOne',
      enum: {
        values: [
          {
            displayName: 'Default',
            value: '',
          },
          {
            displayName: 'xs',
            value: '0rem',
          },
          {
            displayName: 's',
            value: '0.25rem',
          },
          {
            displayName: 'md',
            value: '0.5rem',
          },
          {
            displayName: 'lg',
            value: '1rem',
          },
          {
            displayName: 'xl',
            value: '2rem',
          }
        ],
      },
    },
    textSm: {
      type: 'string',
      displayName: 'text-sm (h6)',
      description: 'Text size: sm',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 20,
      editorSettings: {},
      format: 'shortString',
    },
    secondary: {
      type: 'string',
      displayName: 'color-secondary',
      description: 'Secondary brand color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 30,
      editorSettings: {},
      format: 'shortString',
    },
    radiusBox: {
      type: 'string',
      displayName: 'Radius - Box (card, modal, alert, etc)',
      description: 'Border radius for boxes like card, modal, alert, etc',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 30,
      editorSettings: {},
      format: 'selectOne',
      enum: {
        values: [
          {
            displayName: 'Default',
            value: '',
          },
          {
            displayName: 'xs',
            value: '0rem',
          },
          {
            displayName: 's',
            value: '0.25rem',
          },
          {
            displayName: 'md',
            value: '0.5rem',
          },
          {
            displayName: 'lg',
            value: '1rem',
          },
          {
            displayName: 'xl',
            value: '2rem',
          }
        ],
      },
    },
    textBase: {
      type: 'string',
      displayName: 'text-base (h5 + p)',
      description: 'Text size: base',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 30,
      editorSettings: {},
      format: 'shortString',
    },
    sizeField: {
      type: 'string',
      displayName: 'Size - Field',
      description: 'Base scale size for fields like input, select, tab, etc',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 35,
      editorSettings: {},
      format: 'selectOne',
      enum: {
        values: [
          {
            displayName: 'Default',
            value: '',
          },
          {
            displayName: 'xs',
            value: '0.1875rem',
          },
          {
            displayName: 's',
            value: '0.21875rem',
          },
          {
            displayName: 'md',
            value: '0.25rem',
          },
          {
            displayName: 'lg',
            value: '0.28125rem',
          },
          {
            displayName: 'xl',
            value: '0.3125rem',
          }
        ],
      },
    },
    secondaryContent: {
      type: 'string',
      displayName: 'color-secondary-content',
      description: 'Foreground content color to use on secondary color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 40,
      editorSettings: {},
      format: 'shortString',
    },
    sizeSelector: {
      type: 'string',
      displayName: 'Size - Selector',
      description: 'Base scale size for selectors like checkbox, toggle, badge, etc',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 40,
      editorSettings: {},
      format: 'selectOne',
      enum: {
        values: [
          {
            displayName: 'Default',
            value: '',
          },
          {
            displayName: 'xs',
            value: '0.1875rem',
          },
          {
            displayName: 's',
            value: '0.21875rem',
          },
          {
            displayName: 'md',
            value: '0.25rem',
          },
          {
            displayName: 'lg',
            value: '0.28125rem',
          },
          {
            displayName: 'xl',
            value: '0.3125rem',
          }
        ],
      },
    },
    textLg: {
      type: 'string',
      displayName: 'text-lg (h4)',
      description: 'Text size: lg',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 40,
      editorSettings: {},
      format: 'shortString',
    },
    accent: {
      type: 'string',
      displayName: 'color-accent',
      description: 'Accent brand color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 50,
      editorSettings: {},
      format: 'shortString',
    },
    borderWidth: {
      type: 'float',
      displayName: 'Border Width (px)',
      description: 'Border width of all components',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 50,
      editorSettings: {},
      minimum: 0,
      maximum: 10,
    },
    textXl: {
      type: 'string',
      displayName: 'text-xl (h3)',
      description: 'Text size: xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 50,
      editorSettings: {},
      format: 'shortString',
    },
    depth: {
      type: 'boolean',
      displayName: 'Depth',
      description: 'Adds a depth effect for relevant components',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 59,
      editorSettings: {},
    },
    accentContent: {
      type: 'string',
      displayName: 'color-accent-content',
      description: 'Foreground content color to use on accent color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 60,
      editorSettings: {},
      format: 'shortString',
    },
    text2xl: {
      type: 'string',
      displayName: 'text-2xl (h2)',
      description: 'Text size: 2xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 60,
      editorSettings: {},
      format: 'shortString',
    },
    neutral: {
      type: 'string',
      displayName: 'color-neutral',
      description: 'Neutral dark color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 70,
      editorSettings: {},
      format: 'shortString',
    },
    noise: {
      type: 'boolean',
      displayName: 'Noise',
      description: 'Adds a background noise effect for relevant components',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 70,
      editorSettings: {},
    },
    text3xl: {
      type: 'string',
      displayName: 'text-3xl (h1)',
      description: 'Text size: 3xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 70,
      editorSettings: {},
      format: 'shortString',
    },
    neutralContent: {
      type: 'string',
      displayName: 'color-neutral-content',
      description: 'Foreground content color to use on neutral color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 80,
      editorSettings: {},
      format: 'shortString',
    },
    text4xl: {
      type: 'string',
      displayName: 'text-4xl',
      description: 'Text size: 4xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 80,
      editorSettings: {},
      format: 'shortString',
    },
    text5xl: {
      type: 'string',
      displayName: 'text-5xl',
      description: 'Text size: 5xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 90,
      editorSettings: {},
      format: 'shortString',
    },
    text6xl: {
      type: 'string',
      displayName: 'text-6xl',
      description: 'Text size: 6xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 100,
      editorSettings: {},
      format: 'shortString',
    },
    text7xl: {
      type: 'string',
      displayName: 'text-7xl',
      description: 'Text size: 7xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 110,
      editorSettings: {},
      format: 'shortString',
    },
    text8xl: {
      type: 'string',
      displayName: 'text-8xl',
      description: 'Text size: 8xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 120,
      editorSettings: {},
      format: 'shortString',
    },
    info: {
      type: 'string',
      displayName: 'color-info',
      description: 'Info color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 130,
      editorSettings: {},
      format: 'shortString',
    },
    text9xl: {
      type: 'string',
      displayName: 'text-9xl',
      description: 'Text size: 9xl',
      localized: false,
      required: false,
      group: 'StylesSizes',
      sortOrder: 130,
      editorSettings: {},
      format: 'shortString',
    },
    infoContent: {
      type: 'string',
      displayName: 'color-info-content',
      description: 'Foreground content color to use on info content',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 140,
      editorSettings: {},
      format: 'shortString',
    },
    success: {
      type: 'string',
      displayName: 'color-success',
      description: 'Success color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 150,
      editorSettings: {},
      format: 'shortString',
    },
    successContent: {
      type: 'string',
      displayName: 'color-success-content',
      description: 'Foreground content color to use on success content',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 160,
      editorSettings: {},
      format: 'shortString',
    },
    warning: {
      type: 'string',
      displayName: 'color-warning',
      description: 'Warning color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 170,
      editorSettings: {},
      format: 'shortString',
    },
    warningContent: {
      type: 'string',
      displayName: 'color-warning-content',
      description: 'Foreground content color to use on warning content',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 180,
      editorSettings: {},
      format: 'shortString',
    },
    error: {
      type: 'string',
      displayName: 'color-error',
      description: 'Error color',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 190,
      editorSettings: {},
      format: 'shortString',
    },
    errorContent: {
      type: 'string',
      displayName: 'color-error-content',
      description: 'Foreground content color to use on error content',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 200,
      editorSettings: {},
      format: 'shortString',
    },
    base100: {
      type: 'string',
      displayName: 'color-base-100',
      description: 'Base color of page, used for blank backgrounds',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 210,
      editorSettings: {},
      format: 'shortString',
    },
    base200: {
      type: 'string',
      displayName: 'color-base-200',
      description: 'Base color, darker shade',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 220,
      editorSettings: {},
      format: 'shortString',
    },
    base300: {
      type: 'string',
      displayName: 'color-base-300',
      description: 'Base color, even more darker shade',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 230,
      editorSettings: {},
      format: 'shortString',
    },
    baseContent: {
      type: 'string',
      displayName: 'color-base-content (base text color)',
      description: 'Foreground (text) content color to use on base content',
      localized: false,
      required: false,
      group: 'StylesColors',
      sortOrder: 240,
      editorSettings: {},
      format: 'shortString',
    },
    daisyuiTheme: {
      type: 'string',
      displayName: 'DaisyUI Theme',
      description: 'A free form field to copy/paste the theme generated via the DaisyUI theme generator - https://daisyui.com/theme-generator/',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 499,
      editorSettings: {},
    },
    freeFormStyles: {
      type: 'string',
      displayName: 'Styles (Free Form)',
      description: 'Free-form entry of styles list (for example, from DaisyUI\'s template generator)',
      localized: false,
      required: false,
      group: 'StylesOther',
      sortOrder: 500,
      editorSettings: {},
    },
  },
});

// Function to serialize to JSON (returns a copy that can be safely modified)
export function serializeSiteStylesToJSON() {
  return JSON.parse(JSON.stringify(SiteStylesComponentDefinition));
}
